### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by Jiakui** [flow-dev/simple_open3d_registration#1]
File "simple_registration.py", line 112, in display_inlier_outlier
    inlier_cloud = cloud.select_down_sample(ind)
AttributeError: 'open3d.open3d_pybind.geometry.PointCloud' object has no attribute 'select_down_sample'

the version of open3d is  "0.10.0.1"

**Comment by timeanddoctor** [comment]
Did you deal with the problem?

**Comment by flow-dev** [comment]
Supports open3d version 0.13.0
https://github.com/flow-dev/simple_open3d_registration/commit/6af9d8045a04f5136cb2b91c01e46a5339bf018a
